version: "3.8"
services:
  db:
    container_name: db
    image: postgres:16-alpine
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - ../_data/db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    command:
      - "postgres"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"