basePath: /
definitions:
  models.CreateTaskRequest:
    properties:
      description:
        type: string
      estimate_time:
        type: integer
      parent_task_id:
        type: string
      priority:
        $ref: '#/definitions/models.TaskPriority'
      responsible_user_id:
        type: string
      task_group_id:
        type: string
      title:
        type: string
    type: object
  models.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  models.RegisterRequest:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
  models.TaskPriority:
    enum:
    - LOW
    - MEDIUM
    - HIGH
    - EXTRA
    type: string
    x-enum-varnames:
    - LowTaskPriority
    - MediumTaskPriority
    - HighTaskPriority
    - ExtraTaskPriority
host: localhost:3000
info:
  contact: {}
  description: This is a sample server celler server.
  title: Swagger Example API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: signup data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.LoginRequest'
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
  /auth/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: signup data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.RegisterRequest'
      responses:
        "201":
          description: Created
          schema:
            type: integer
        "409":
          description: Conflict
        "500":
          description: Internal Server Error
  /task:
    post:
      consumes:
      - application/json
      description: create task
      parameters:
      - description: Authentication header
        in: header
        name: Authorization
        required: true
        type: string
      - description: create task body
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.CreateTaskRequest'
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
  /task/{id}:
    get:
      description: task by id
      parameters:
      - description: Authentication header
        in: header
        name: Authorization
        required: true
        type: string
      - description: task id
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
  /tasks:
    get:
      description: list of user tasks
      parameters:
      - description: Authentication header
        in: header
        name: Authorization
        required: true
        type: string
      - description: task title
        in: query
        name: title
        type: string
      - description: task id
        in: query
        name: id
        type: string
      - description: task created_at
        in: query
        name: created_at
        type: string
      - description: task parent_task_id
        in: query
        name: parent_task_id
        type: string
      - description: task creater_id
        in: query
        name: creater_id
        type: string
      - description: task responsible_user_id
        in: query
        name: responsible_user_id
        type: string
      - description: task title
        in: query
        name: title
        type: string
      - description: task description
        in: query
        name: description
        type: string
      - description: task status
        in: query
        name: status
        type: string
      - description: task task_group_id
        in: query
        name: task_group_id
        type: string
      - description: task priority
        in: query
        name: priority
        type: string
      - description: task estimate_time
        in: query
        name: estimate_time
        type: string
      - description: task time_spent
        in: query
        name: time_spent
        type: string
      - description: task deleted_at
        in: query
        name: deleted_at
        type: string
      - description: task archived
        in: query
        name: archived
        type: boolean
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
securityDefinitions:
  ApiKeyAuth:
    type: basic
swagger: "2.0"
